/home/applications/miniconda2.7/4.2.12/miniconda2/bin/python: can't open file '/home/data/nbc/data-analysis/env3/bin/conda': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "run_first_level.py", line 15, in <module>
    import matplotlib.pyplot as plt
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/matplotlib/figure.py", line 36, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/matplotlib/axes.py", line 39, in <module>
    import matplotlib.tri as mtri
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/matplotlib/tri/__init__.py", line 5, in <module>
    from triangulation import *
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/matplotlib/tri/triangulation.py", line 3, in <module>
    import matplotlib._tri as _tri
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/applications/python/2.7.5/lib/python2.7/site-packages/matplotlib/_tri.so)
